package com.jiuyi.net.client;

import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.ws.rs.POST;
import javax.ws.rs.Path;

import com.jiuyi.net.message.onlinebank.CfcaSingleTransferReqMsg;
import com.jiuyi.net.message.onlinebank.CfcaSingleTransferRspMsg;
import com.jiuyi.net.message.onlinebank.CheckDebitCardReqMsg;
import com.jiuyi.net.message.onlinebank.CheckDebitCardRspMsg;
import com.jiuyi.net.message.onlinebank.MemberCfcaAccReqMsg;
import com.jiuyi.net.message.onlinebank.MemberCfcaAccRspMsg;


/**
 * This class was generated by Apache CXF 2.4.0 2011-09-08T21:29:30.030+08:00
 * Generated source version: 2.4.0
 * 
 */

@WebService(targetNamespace = "http://server.net.uxun.com/", name = "IJFYFrontService")
public interface IEpayFrontService {

    
    
    /**
	 * 检查它行卡信息是否符合（是否可以实名认证,提供给e住e行）
	 * @param reqMsg
	 * @return
	 * @author lix 2014-12-25 
	 */
	@WebResult(name = "uxunmsg")
	@POST
	@Path("/checkMembercfcaCard")
	public MemberCfcaAccRspMsg checkMembercfcaCard(@WebParam(name = "uxunmsg")MemberCfcaAccReqMsg reqMsg);
	
    /**
	 * 检查本行卡信息是否符合（是否可以实名认证,提供给e住e行）
	 * @param reqMsg
	 * @return
	 * @author sunzb
	 */
	@WebResult(name = "uxunmsg")
	@POST
	@Path("/checkDebitCard")
	public CheckDebitCardRspMsg checkDebitCard(@WebParam(name = "uxunmsg")CheckDebitCardReqMsg reqMsg);
	
	/**
	 * 中金机构支付账户单笔转账（提供给e住e行）
	 * @param reqMsg
	 * @return
	 * @author lix 2014-12-25 
	 */
	@WebResult(name = "uxunmsg")
	@POST
	@Path("/CfcaSingleTransfer")
	public CfcaSingleTransferRspMsg CfcaSingleTransfer(@WebParam(name = "uxunmsg")CfcaSingleTransferReqMsg reqMsg);

}
