package com.jiuyi.net.client;

import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.ws.rs.POST;
import javax.ws.rs.Path;

import com.jiuyi.net.message.unioncollect.ThirdCardCollectReqMsg;
import com.jiuyi.net.message.unioncollect.ThirdCardCollectRspMsg;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2015-11-03T17:44:40.854+08:00
 * Generated source version: 2.4.0
 * 
 */

@WebService(targetNamespace = "http://server.net.uxun.com/", name = "IUnionCollectAndPayNetNewService")
public interface IUnionCollectAndPayNetNewService {

	/**
	 * 他行卡代收
	 * @param reqMsg
	 * @return
	 */
	@WebResult(name = "uxunmsg")
	@POST
	@Path("/thirdCardCollect")
	public ThirdCardCollectRspMsg thirdCardCollect(@WebParam(name = "uxunmsg")  ThirdCardCollectReqMsg reqMsg);
	
}
