package com.jiuyi.net.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.jiuyi.net.message.onlinebank.BankCardBindReqMsg;
import com.jiuyi.net.message.onlinebank.BankCardBindRspMsg;
import com.jiuyi.net.message.unioncollect.FundTransQryReqMsg;
import com.jiuyi.net.message.unioncollect.FundTransQryRspMsg;
import com.jiuyi.net.message.unioncollect.FundTransferRspMsg;
import com.jiuyi.net.message.unioncollect.InterestQryReqMsg;
import com.jiuyi.net.message.unioncollect.InterestQryRspMsg;
import com.jiuyi.net.message.unioncollect.InterestTransferReqMsg;
import com.jiuyi.net.message.unioncollect.InterestTransferRspMsg;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2015-03-24T17:44:40.854+08:00
 * Generated source version: 2.4.0
 * 
 */

@WebService(targetNamespace = "http://server.net.uxun.com/", name = "IUnionCollectAndPayNetService")
public interface IUnionCollectAndPayNetService {

	@RequestWrapper(localName = "fundTransfer", targetNamespace = "http://server.net.uxun.com/", className = "com.jiuyi.net.message.unioncollect.FundTransfer")
	@WebMethod
	@ResponseWrapper(localName = "fundTransferResponse", targetNamespace = "http://server.net.uxun.com/", className = "com.jiuyi.net.message.unioncollect.FundTransferResponse")
	public FundTransferRspMsg fundTransfer(
	    @WebParam(name = "uxunmsg", targetNamespace = "")
	    com.jiuyi.net.message.unioncollect.FundTransferReqMsg uxunmsg,
	    @WebParam(mode = WebParam.Mode.OUT, name = "uxunmsg", targetNamespace = "")
	    javax.xml.ws.Holder<FundTransferRspMsg> uxunmsg1
	);
	
	/**
	 * 利息查询
	 * @param reqMsg
	 * @return
	 */
	@WebResult(name = "uxunmsg")
	@POST
	@Path("/interestQry")
	public InterestQryRspMsg interestQry(@WebParam(name = "uxunmsg") InterestQryReqMsg reqMsg);
	
	/**
	 * 流水查询
	 * @param reqMsg
	 * @return
	 */
	@WebResult(name = "uxunmsg")
	@POST
	@Path("/fundTransQry")
	public FundTransQryRspMsg fundTransQry(@WebParam(name = "uxunmsg") FundTransQryReqMsg reqMsg);

	/**
	 * 
	 * <p>利息划转</p>
	 * @param uxunmsg
	 * @param uxunmsg1
	 * @author guoyuzhuang
	 */
	@WebResult(name = "uxunmsg")
	@POST
	@Path("/interestTransfer")
	public InterestTransferRspMsg interestTransfer(@WebParam(name = "uxunmsg") InterestTransferReqMsg reqMsg);
	
	/**
	 * 他行卡绑卡
	 * @param reqMsg
	 * @return
	 * @author baizilin
	 */
	@WebResult(name = "uxunmsg")
	@POST
	@Path("/bankCardBind")
	public BankCardBindRspMsg bankCardBind(@WebParam(name = "uxunmsg") BankCardBindReqMsg reqMsg);
}
