<%@taglib uri="/WEB-INF/tlds/c.tld" prefix="c"%>
<%@taglib uri="/WEB-INF/tlds/fn.tld" prefix="fn"%>
<%@taglib uri="/WEB-INF/tlds/struts-tags.tld" prefix="s"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="s2" uri="/struts-tags" %>
<%@ page isELIgnored="false"%> 
<%--图片服务器地址  add by 2016-04-22 陈林--%>
<c:set var="imgPath" value="http://98.11.0.98/cportalFileServer/files/"/>