
package com.jiuyi.net.client.zx.webservice.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.9
 * Fri Sep 16 14:15:01 CST 2016
 * Generated source version: 2.2.9
 * 
 */
 
public class IBankService_IBankServicePort_Server{

    protected IBankService_IBankServicePort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new IBankServiceImpl();
        String address = "http://localhost/AdvanceSaleHouseWebserviceDemo/services/bankServer";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new IBankService_IBankServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
