
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.jiuyi.net.client.zx.webservice.client;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.2.9
 * Fri Sep 16 14:15:01 CST 2016
 * Generated source version: 2.2.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "IBankServiceService",
                      portName = "IBankServicePort",
                      targetNamespace = "http://service.ws.mams.com/",
                      wsdlLocation = "http://localhost/AdvanceSaleHouseWebserviceDemo/services/bankServer?wsdl",
                      endpointInterface = "com.jiuyi.net.client.zx.webservice.client.IBankService")
                      
public class IBankServiceImpl implements IBankService {

    private static final Logger LOG = Logger.getLogger(IBankServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.mams.webservice.client.IBankService#qurAccountInfo(java.lang.String  accountNo ,)java.lang.String  queryDate ,)java.lang.String  startDate ,)java.lang.String  endDate )*
     */
    public BankData qurAccountInfo(java.lang.String accountNo,java.lang.String queryDate,java.lang.String startDate,java.lang.String endDate) { 
        LOG.info("Executing operation qurAccountInfo");
//        System.out.println(accountNo);
//        System.out.println(queryDate);
//        System.out.println(startDate);
//        System.out.println(endDate);
        try {
           BankData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.mams.webservice.client.IBankService#qurOrderInfo(java.lang.String  arg0 )*
     */
    public java.lang.String qurOrderInfo(java.lang.String arg0) { 
        LOG.info("Executing operation qurOrderInfo");
//        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
