
package com.jiuyi.net.client.zx.webservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Fri Sep 16 14:15:01 CST 2016
 * Generated source version: 2.2.9
 * 
 */

public final class IBankService_IBankServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.ws.mams.com/", "IBankServiceService");

    private IBankService_IBankServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = IBankServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IBankServiceService ss = new IBankServiceService(wsdlURL, SERVICE_NAME);
        IBankService port = ss.getIBankServicePort();  
        
        {
        System.out.println("Invoking qurAccountInfo...");
        java.lang.String _qurAccountInfo_accountNo = "";
        java.lang.String _qurAccountInfo_queryDate = "";
        java.lang.String _qurAccountInfo_startDate = "";
        java.lang.String _qurAccountInfo_endDate = "";
        BankData _qurAccountInfo__return = port.qurAccountInfo(_qurAccountInfo_accountNo, _qurAccountInfo_queryDate, _qurAccountInfo_startDate, _qurAccountInfo_endDate);
        System.out.println("qurAccountInfo.result=" + _qurAccountInfo__return);


        }
        {
        System.out.println("Invoking qurOrderInfo...");
        java.lang.String _qurOrderInfo_arg0 = "";
        java.lang.String _qurOrderInfo__return = port.qurOrderInfo(_qurOrderInfo_arg0);
        System.out.println("qurOrderInfo.result=" + _qurOrderInfo__return);


        }

        System.exit(0);
    }

}
