
/*
 * 
 */

package com.jiuyi.net.client.zx.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Fri Sep 16 14:15:01 CST 2016
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "IBankServiceService", 
                  wsdlLocation = "http://localhost/AdvanceSaleHouseWebserviceDemo/services/bankServer?wsdl",
                  targetNamespace = "http://service.ws.mams.com/") 
public class IBankServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.ws.mams.com/", "IBankServiceService");
    public final static QName IBankServicePort = new QName("http://service.ws.mams.com/", "IBankServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/AdvanceSaleHouseWebserviceDemo/services/bankServer?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost/AdvanceSaleHouseWebserviceDemo/services/bankServer?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public IBankServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IBankServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IBankServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns IBankService
     */
    @WebEndpoint(name = "IBankServicePort")
    public IBankService getIBankServicePort() {
        return super.getPort(IBankServicePort, IBankService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBankService
     */
    @WebEndpoint(name = "IBankServicePort")
    public IBankService getIBankServicePort(WebServiceFeature... features) {
        return super.getPort(IBankServicePort, IBankService.class, features);
    }

}
